mode = "full" # required, stringï¼Œå€¼åªèƒ½ä¸º full tmpl nodes, ä¸å¯ä»¥ä¸ºç©º
tmpl_path = "tmpl/RealDNS_Tun_RuleSet.json" # required, string, ä¸å¯ä»¥ä¸ºç©º
config_save_path = "./config.json" # required, string, å¯ä»¥ä¸ºç©º
nodes_save_path = "./nodes.json" # required, string, å¯ä»¥ä¸ºç©º

# optional è¦ä¹ˆä¸å†™ï¼Œå†™å°±éœ€è¦å†™å…¨ï¼Œæ¯ä¸€é¡¹éƒ½ä¸èƒ½ä¸ºç©º
[cloudflare] 
CLOUDFLARE_ACCOUNT_ID="xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
CLOUDFLARE_API_KEY="xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
CLOUDFLARE_EMAIL="xxxxx@gmail.com" # å¿…é¡»æ˜¯åˆæ³•çš„é‚®ç®±åœ°å€
CLOUDFLARE_KV_NAMESPACE_ID="xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
# æ•°ç»„
# æ¯ä¸ª token ä»…ç”±æ•°å­—å’Œå°å†™å­—æ¯ç»„æˆ
# æ¯ä¸ª token é•¿åº¦éœ€å¤§äºç­‰äº 32
SUBSCRIBE_USER_TOKEN=[
    "y5vswuhsfrona3y464yii8xc8zk6ffv7",
    "6vunx1j0y3qont9vvqyf421nvj1psfnx",
    "dngg9c4batg7wbxbfhs44hbx0jvezhrp"
]

# required, è‡³å°‘è¦æœ‰ä¸€ä¸ª [[subscribe]]ï¼Œ
# å¦‚æœä¸€ä¸ªéƒ½æ²¡æœ‰ï¼Œåˆ™æŠ¥é”™
# url å’Œ tag å¿…é¡»å­˜åœ¨ï¼Œä¸”å€¼ä¸èƒ½ä¸ºç©º
# å‰©ä½™é¡¹ï¼Œå¿…é¡»å­˜åœ¨ï¼Œä½†å€¼å¯ä»¥ä¸ºç©º
[[subscribe]]
url = "https://xxx.com/subscribe?token=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
tag = "AA"
prefix = "A-"
exclude_keywords="è‡ªåŠ¨|ç½‘ç«™|å®˜ç½‘|æµé‡|è¿‡æœŸ|åˆ°æœŸ|æ”¶è—|è¶…æ—¶|é‡ç½®"
exclude_protocol = "ssh" 

[[subscribe]]
url = "https://xxxx.com/subscribe?token=e4e71faf169ea29b7d49e7cd301961ee"
tag = "AA"
prefix = "B-"
exclude_keywords="è‡ªåŠ¨|ç½‘ç«™|å®˜ç½‘|æµé‡|è¿‡æœŸ|åˆ°æœŸ|æ”¶è—|è¶…æ—¶|é‡ç½®"
exclude_protocol = "ssh" 

# optional è¦ä¹ˆä¸å†™ï¼Œå†™å°±éœ€è¦å†™å…¨ï¼Œæ¯ä¸€é¡¹éƒ½ä¸èƒ½ä¸ºç©º
[[sort]]
range = "Proxy"
keywords = [ # æ•°ç»„é•¿åº¦è¦å¤§äºç­‰äº 2
    "auto",
    "direct",
    "ğŸ‡­ğŸ‡°|HK|hk|é¦™æ¸¯|æ¸¯|HongKong",
    "ğŸ‡¹ğŸ‡¼|TW|tw|å°æ¹¾|è‡ºç£|å°|Taiwan",
    "ğŸ‡¸ğŸ‡¬|SG|sg|æ–°åŠ å¡|ç‹®|Singapore",
    "ğŸ‡¯ğŸ‡µ|JP|jp|æ—¥æœ¬|æ—¥|Japan",
    "ğŸ‡ºğŸ‡¸|US|us|ç¾å›½|ç¾|United States",
    "others",
]

[[sort]]
range = "Jpan|Singapore|HongKong"
keywords = [
    "ä¸“çº¿",
    "äºšé©¬é€Š",
    "æ¬ç“¦å·¥",
    "0.1å€ç‡",
    "IPv6|ipv6",
    "others",
]